[package]
name = "foxglove-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
dbc-codegen = "0.3.0"
flatbuffers = "25.12.19"
foxglove = "0.16.6"
socketcan = "3.5.0"

[dependencies.nokhwa]
version = "0.10"
# Use the native input backends, enable WGPU integration
features = ["input-native"]
