[project]
name = "flatbuffer-gen-tool"
version = "0.1.0"
description = "It takes a DBC and makes a .fbs for serializing flatbuffers"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["cantools>=41.0.2"]
